image: nopreserveroot/texlive-full

build:
  script:
    - cd latex-code/exercise
    - latexmk -pdf exercise
    - cd ../slides
    - latexmk slides
  artifacts:
    paths:
      - latex-code/exercise/exercise.pdf
      - latex-code/slides/slides.pdf
